object MustacheConstants {

    /**
     * TEMPLATING
     */

    const val COMPANY_HEADER = "company_header"
    const val AUTHOR = "author"
    const val DATE_DAY = "date_day"
    const val DATE_MONTH = "date_month"
    const val DATE_YEAR = "date_year"
    const val TABLENAME = "tableName"
    const val TABLENAME_ORIGINAL = "tableName_original"
    const val TABLENAME_LOWERCASE = "tableName_lowercase"
    const val TABLENAMES = "tableNames"
    const val TABLENAMES_LAYOUT = "tableNames_layout"
    const val TABLENAMES_RELATIONS = "tableNames_relations"
    const val TABLENAMES__LAYOUT_RELATIONS = "tableNames_layout_relations"
    const val TABLENAMES_WITHOUT_RELATIONS = "tableNames_without_relations"
    const val TABLENAMES_RELATIONS_DISTINCT = "tableNames_relations_distinct"
    const val TABLENAMES_LOWERCASE = "tableNames_lowercase"
    const val TABLENAMES_NAVIGATION = "tableNames_navigation"
    const val FIELDS = "fields"
    const val FIRST_FIELD = "first_field"
    const val FORM_FIELDS = "form_fields"
    const val IMAGE_FIELD_NAME = "imageFieldName"
    const val IMAGE_TABLE_NAME = "imageTableName"
    const val IMAGE_KEY_ACCESSOR = "imageKeyAccessor"
    const val APP_NAME_WITH_CAPS = "app_name_with_caps"
    const val PACKAGE = "package"
    const val REMOTE_ADDRESS = "remote_address"
    const val ANDROID_SDK_PATH = "android_sdk_path"
    const val CACHE_4D_SDK_PATH = "cache_4d_sdk_path"
    const val TYPES_AND_TABLES = "types_and_tables"
    const val ENTITY_CLASSES = "entity_classes"
    const val RELATION_SOURCE = "relation_source"
    const val RELATION_TARGET = "relation_target"
    const val RELATION_SAME_TYPE = "relation_same_type"
    const val RELATION_NAME = "relation_name"
    const val RELATIONS = "relations"
    const val RELATIONS_IMPORT = "relations_import"

    const val COLORS_DEFINED = "logo_colors_defined"
    const val COLOR_PRIMARY_NEUTRAL = "color_primary_neutral"
    const val COLOR_PRIMARY_DARKER = "color_primary_darker_08"
    const val COLOR_PRIMARY_DARKER_PLUS = "color_primary_darker_06"
    const val COLOR_PRIMARY_DARKER_PLUS_PLUS = "color_primary_darker_04"
    const val COLOR_PRIMARY_LIGHTER = "color_primary_lighter_12"
    const val COLOR_PRIMARY_LIGHTER_PLUS = "color_primary_lighter_14"
    const val COLOR_PRIMARY_LIGHTER_PLUS_PLUS = "color_primary_lighter_16"

    const val THEME_COLOR_PRIMARY = "theme_color_primary"
    const val THEME_COLOR_PRIMARY_DARKER = "theme_color_primary_darker"
    const val THEME_COLOR_PRIMARY_LIGHTER = "theme_color_primary_lighter"
    const val THEME_COLOR_ON_PRIMARY = "theme_color_on_primary"
}
