variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_SDK_TOOLS: "4333796"
  ANDROID_BUILD_TOOLS: "29.0.2"
  AVD_SDK: "29"
  AVD_TAG: "google_apis_playstore"
  AVD_ARCH: "x86"

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - ./checkConf.sh
  script:
    - mkdir -p build
    - ./compile.sh build
  tags:
    - osx
  artifacts:
    paths:
     - build/

test:
  stage: test
  script:
    - curl http://QA:quality@srv-build:8111/repository/download/id4dmobile_QMobile_Main_Android_TestEnv/.lastSuccessful/androidtestenv.zip -o androidtestenv.zip
    - unzip androidtestenv.zip -d test/
    - export MOBILE_COMPONENT_PATH=./test/4D\ Mobile\ App
    - export QMOBILE_HOME=./test/
    - ./tests.sh ./test/dataForCreateProject
  tags:
    - osx


