data class TemplateFormFieldFiller(
    val name: String,
    val label: String,
    val shortLabel: String,
    val viewId: Int,
    val isRelation: Boolean,
    val isImage: Boolean,
    val accessor: String,
    val isCustomFormat: Boolean,
    val isImageNamed: Boolean,
    val formatType: String,
    val fieldName: String,
    val imageKeyAccessor: String,
    val fieldTableName: String,
    val imageWidth: Int,
    val imageHeight: Int,
    val hasIcon: Boolean,
    val iconPath: String
)
