//INCLUDE version.kt
//INCLUDE CatalogDef.kt
//INCLUDE FileHelper.kt
//INCLUDE MustacheHelper.kt
//INCLUDE PathHelper.kt
//INCLUDE ProjectEditor.kt
//INCLUDE constants/Clikt.kt
//INCLUDE constants/DefaultValues.kt
//INCLUDE constants/ExitCodes.kt
//INCLUDE constants/FeatureFlagConstants.kt
//INCLUDE constants/FileHelperConstants.kt
//INCLUDE constants/MustacheConstants.kt
//INCLUDE constants/PathHelperConstants.kt
//INCLUDE constants/ProjectEditorConstants.kt
//INCLUDE database/AppInfoHelper.kt
//INCLUDE database/CreateDatabaseTask.kt
//INCLUDE database/DbConstants.kt
//INCLUDE database/GroovyInteroperability.kt
//INCLUDE database/SqlQueryBuilder.kt
//INCLUDE database/StaticDatabase.kt
//INCLUDE database/StaticDataInitializer.kt
//INCLUDE models/Actions.kt
//INCLUDE models/AppData.kt
//INCLUDE models/AppInfo.kt
//INCLUDE models/InputControlDataSource.kt
//INCLUDE models/SectionField.kt
//INCLUDE models/fillers/TemplateFieldFiller.kt
//INCLUDE models/fillers/TemplateFormatterFiller.kt
//INCLUDE models/fillers/TemplateFormFieldFiller.kt
//INCLUDE models/fillers/TemplateInputControlFiller.kt
//INCLUDE models/fillers/TemplateLayoutFiller.kt
//INCLUDE models/fillers/TemplateLayoutTypeFiller.kt
//INCLUDE models/fillers/TemplatePermissionFiller.kt
//INCLUDE models/fillers/TemplateRelationDefFiller.kt
//INCLUDE models/fillers/TemplateRelationFiller.kt
//INCLUDE models/fillers/TemplateRelationFillerForEachLayout.kt
//INCLUDE models/fillers/TemplateTableFiller.kt
//INCLUDE models/projecteditor/DataModel.kt
//INCLUDE models/projecteditor/Field.kt
//INCLUDE models/projecteditor/FieldMapping.kt
//INCLUDE models/projecteditor/Form.kt
//INCLUDE models/projecteditor/FormType.kt
//INCLUDE models/projecteditor/Relation.kt
//INCLUDE models/projecteditor/RelationType.kt
//INCLUDE models/projecteditor/VariableType.kt
//INCLUDE models/TableInfo.kt
//INCLUDE utils/Color.kt
//INCLUDE utils/FeatureChecker.kt
//INCLUDE utils/Formatters.kt
//INCLUDE utils/StringHelper.kt
//INCLUDE utils/JSONExt.kt
//INCLUDE utils/JSONExtDataModel.kt
//INCLUDE utils/JSONExtField.kt
//INCLUDE utils/JSONExtForm.kt
//INCLUDE utils/JSONExtNavigation.kt
//INCLUDE utils/Log.kt
//INCLUDE utils/XmlTemplateFixer.kt
//INCLUDE utils/ZipManager.kt