name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: sdkman/sdkman-action@main
      id: sdkman
      with:
        candidate: java
        version: 17.0.7-amzn
    - name: Set up Kscript
      run: |
          source $HOME/.sdkman/bin/sdkman-init.sh
          sdk install kscript 4.2.2
          sdk use kscript 4.2.2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # - name: Setup Gradle
    #   uses: gradle/gradle-build-action@v2

    - name: Build 
      run: |
          source $HOME/.sdkman/bin/sdkman-init.sh
          ./build.sh
